# Generated by Django 5.2.9 on 2025-12-28 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jamath", "0006_membershipconfig_household_label_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicerequest",
            name="description",
            field=models.TextField(
                blank=True, help_text="Detailed description of the request", null=True
            ),
        ),
    ]
