# Generated by Django 5.2.9 on 2025-12-28 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jamath", "0007_alter_servicerequest_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="announcement",
            name="status",
            field=models.CharField(
                choices=[("DRAFT", "Draft"), ("PUBLISHED", "Published")],
                default="PUBLISHED",
                max_length=20,
            ),
        ),
    ]
