# Generated by Django 5.2.9 on 2025-12-28 14:14

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jamath", "0008_announcement_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("contact_person", models.CharField(blank=True, max_length=100)),
                ("phone", models.CharField(blank=True, max_length=15)),
                ("address", models.TextField(blank=True)),
                (
                    "gstin",
                    models.CharField(
                        blank=True, help_text="GST Identification Number", max_length=15
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="JournalEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "voucher_number",
                    models.CharField(
                        help_text="e.g., RCP-2025-001", max_length=50, unique=True
                    ),
                ),
                (
                    "voucher_type",
                    models.CharField(
                        choices=[
                            ("RECEIPT", "Receipt Voucher"),
                            ("PAYMENT", "Payment Voucher"),
                            ("JOURNAL", "Journal Entry"),
                        ],
                        max_length=20,
                    ),
                ),
                ("date", models.DateField()),
                (
                    "narration",
                    models.TextField(help_text="Description of the transaction"),
                ),
                (
                    "donor_name_manual",
                    models.CharField(
                        blank=True, help_text="For guest donors", max_length=200
                    ),
                ),
                (
                    "donor_pan",
                    models.CharField(
                        blank=True,
                        help_text="Required for amounts > ₹2000",
                        max_length=10,
                    ),
                ),
                (
                    "donor_intent",
                    models.TextField(
                        blank=True,
                        help_text="Specific direction like 'For buying fans only'",
                    ),
                ),
                ("vendor_invoice_no", models.CharField(blank=True, max_length=50)),
                ("vendor_invoice_date", models.DateField(blank=True, null=True)),
                (
                    "proof_document",
                    models.FileField(
                        blank=True,
                        help_text="Required for amounts > ₹500",
                        null=True,
                        upload_to="vouchers/proofs/",
                    ),
                ),
                (
                    "payment_mode",
                    models.CharField(
                        choices=[
                            ("CASH", "Cash"),
                            ("NEFT", "Bank Transfer (NEFT/IMPS)"),
                            ("UPI", "UPI"),
                            ("CHEQUE", "Cheque"),
                        ],
                        default="CASH",
                        max_length=20,
                    ),
                ),
                (
                    "is_finalized",
                    models.BooleanField(
                        default=False, help_text="Locked entries cannot be modified"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="journal_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "donor",
                    models.ForeignKey(
                        blank=True,
                        help_text="For Receipt vouchers",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="donations",
                        to="jamath.member",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        help_text="For Payment vouchers",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payments",
                        to="jamath.supplier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Journal Entry",
                "verbose_name_plural": "Journal Entries",
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Ledger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="e.g., 1001, 2001", max_length=20, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("ASSET", "Asset"),
                            ("LIABILITY", "Liability"),
                            ("INCOME", "Income"),
                            ("EXPENSE", "Expense"),
                            ("EQUITY", "Equity/Corpus"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "fund_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ZAKAT", "Restricted - Zakat"),
                            ("SADAQAH", "Restricted - Sadaqah"),
                            ("CONSTRUCTION", "Restricted - Construction"),
                            ("GENERAL", "Unrestricted - General"),
                        ],
                        help_text="Required for Income/Expense accounts",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "is_system",
                    models.BooleanField(
                        default=False, help_text="System accounts cannot be deleted"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="jamath.ledger",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ledger Account",
                "verbose_name_plural": "Chart of Accounts",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="JournalItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "debit_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "credit_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "particulars",
                    models.CharField(
                        blank=True,
                        help_text="Additional line description",
                        max_length=200,
                    ),
                ),
                (
                    "journal_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="jamath.journalentry",
                    ),
                ),
                (
                    "ledger",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="journal_items",
                        to="jamath.ledger",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
    ]
